### ISSUE TITLE
1.0 Checklist

### ISSUE THREAD

**Issue by lambdadog** [lambdadog/rescript-tree-sitter-mode#1]
# Tasks

 - [ ] **Basic mode features** - should be implementable while maintaining current complexity
   + [X] Highlighting
     - [ ] Revise current highlighting queries as per [emacs conventions](https://emacs-tree-sitter.github.io/syntax-highlighting/#tree-sitter-langs). The existing highlighting queries are from the grammar itself (although the grammar was built specifically for NeoVim usage, rather than GitHub usage) so it may be worth writing custom queries.
   + [ ] #2 - [tree-sitter-indent](https://github.com/emacsmirror/tree-sitter-indent) has a number of problems that make it not suitable for my use-cases. See https://github.com/helix-editor/helix/pull/1562 and [**[helix-editor/helix]** Adding Indent Queries](https://github.com/helix-editor/helix/blob/master/book/src/guides/indent.md) for an example of query-based indentation.
   + [ ] Auto-formatting - [format-all](https://github.com/lassik/emacs-format-all-the-code) already seems to have support, but it would be nice to centralize. Writing a formatter for [reformatter](https://github.com/purcell/emacs-reformatter) may also be desired.
 - [ ] **Rich IDE-like features** - will require integration of language server (see [rescript-vscode](https://github.com/rescript-lang/rescript-vscode))
   + [ ] Completion
   + [ ] Built-in watcher
   + [ ] Flymake/Flycheck support
   + [ ] [TBC]
